Configuración As screen:

    Color1 As rectangle:
        Fill: =RGBA(160, 144, 96, 1)
        Width: =210.83
        X: =56.22
        Y: =40
        ZIndex: =1

    Color2 As rectangle:
        Fill: =Color.White
        Width: =210.83
        X: =328.90
        Y: =40
        ZIndex: =2

    Color3 As rectangle:
        Fill: =RGBA(153, 165, 175, 1)
        Width: =210.83
        X: =581.90
        Y: =40
        ZIndex: =3

    ColorSuccess As rectangle:
        Fill: =RGBA(133, 202, 93, 1)
        Width: =210.83
        X: =56.22
        Y: =222
        ZIndex: =4

    ColorError As rectangle:
        Fill: =RGBA(255, 89, 118, 1)
        Width: =210.83
        X: =328.90
        Y: =222
        ZIndex: =5

    ColorWarning As rectangle:
        Fill: =RGBA(255, 250, 129, 1)
        Width: =210.83
        X: =581.90
        Y: =222
        ZIndex: =6

    AppFont As label:
        Font: =Font.'Segoe UI'
        PaddingRight: =7.03
        PaddingTop: =7.03
        Size: =18.27
        Text: ="Fuente de Texto"
        Width: =210.83
        X: =56.22
        Y: =376
        ZIndex: =7

    Logo As image:
        Height: =184
        Image: ='logo-cliente'
        Width: =428
        X: =968
        Y: =86
        ZIndex: =8

